attendance/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('att_list/', views.att_list, name='att_list'),
    path('view_timecard/', views.view_timecard, name='view_timecard'),
    path('ajax_on_change_tcf/', views.ajax_on_change_tcf, name='ajax_on_change_tcf'),
]

factory/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('orders/', include('orders.urls')),
    path('notice/', include('notice.urls')),
    path('attendance/', include('attendance.urls')),
    path('report/', include('report.urls')),
    path('projectmanagement/', include('projectmanagement.urls')),
    path('payroll/', include('payroll.urls')),
    path('trashcan/', include('trashcan.urls'))
]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('login/', views.login, name='login'),
    path('userappend/', views.userappend, name='userappend'),
    path('user_normal_select/', views.user_normal_select, name='user_normal_select'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('user_list/', views.user_list, name='user_list'),
    path('user_select/', views.user_select, name='user_select'),
    # path('attendence_list/<int:user_pk>', views.attendence_list, name='attendence_list'),
    # path('attendence_lists/', views.attendence_lists, name='attendence_lists'),
    path('position_lists/', views.position_lists, name='position_lists'),
    path('staff_type_modify/<int:position_pk>', views.staff_type_modify, name='staff_type_modify'),
    path('staff_type_add/', views.staff_type_add, name='staff_type_add'),
    path('staff_type_delete/<int:position_pk>', views.staff_type_delete, name='staff_type_delete'),
    path('salary_list/<int:user_pk>', views.salary_list, name='salary_list'),
    path('salary_lists/', views.salary_lists, name='salary_lists'),
    path('caculate_salary/', views.caculate_salary, name='caculate_salary'),
    path('salary_normal_select/', views.salary_normal_select, name='salary_normal_select'),
    path('salary_select/', views.salary_select, name='salary_select'),
    #path('change_nickname/', views.change_nickname, name='change_nickname'),
    #path('bind_email/', views.bind_email, name='bind_email'),
    #path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('change_password/', views.change_password, name='change_password'),
    #path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('user_delete/<int:user_pk>', views.user_delete, name='user_delete'),
    path('user_modify/<int:user_pk>', views.usermodify, name='user_modify'),
    # path('attendence_append/', views.attendence_append, name='attendence_append'),
    # path('attendence_select/', views.attendence_select, name='attendence_select'),
    # path('attendence_delete/<int:attendence_pk>', views.attendence_delete, name='attendence_delete'),
    # path('attendence_modify/<int:attendence_pk>', views.attendence_modify, name='attendence_modify'),
    path('sel_pay_m', views.sel_pay_m, name='sel_pay_m'),
]

attendance/models.py
from django.db import models
from django.contrib.auth.models import User
from projectmanagement.models import Project

# Create your models here.


class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="姓名")
    att_date=models.DateField(auto_now_add=False, verbose_name="日期")
    work_time=models.FloatField()
    proj_occ=models.ForeignKey(Project, on_delete=models.DO_NOTHING, verbose_name="参与项目", null=True)

    def get_user_name(self):
        if User.objects.filter(id=self.user.pk).exists():
            name = User.objects.get(id=self.user.pk).username
            return name
        else:
            return None

    def get_proj_name(self):
        if not self.proj_occ:
            return '无项目'
        if Project.objects.filter(pk=self.proj_occ.pk).exists():
            name = Project.objects.get(pk=self.proj_occ.pk).proj_name
            return name
        else:
            return None

attendance/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.forms import widgets
from projectmanagement.models import Project



class TimecardForm(forms.Form):
    ps = Project.objects.all()
    proj = [('不选择项目', '不选择项目')]
    for p in ps:
        proj.append((p.proj_name, p.proj_name))
    att_date = forms.DateField(
        label='选择日期',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.DateInput(attrs={'type': 'date', 'onchange':'on_change_tcf()'})
    )

    work_time = forms.FloatField(
        label='工作时长',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入工作时长'})
    )

    proj_occ = forms.CharField(
        label='项目名称',
        widget=forms.Select(choices=proj),
    )

attendance/views.py
from django.urls import reverse
from django.shortcuts import render,get_object_or_404, redirect
from .forms import TimecardForm
from .models import Attendance
from projectmanagement.models import Project
from django.http.response import HttpResponse, JsonResponse

# Create your views here.

def att_list(request):
    usr = request.user
    if usr.is_authenticated:
        if usr.get_staff_type() != '管理员':
            att_list = Attendance.objects.filter(user=usr)
        else:
            att_list = Attendance.objects.all()
        context = {}
        context['att_list'] = att_list
        return render(request, 'att_list.html', context)
    else:
        return redirect(reverse('login'))


def view_timecard(request):
    usr = request.user
    timecard_form = TimecardForm()
    if usr.is_authenticated:
        if request.method == 'POST':
            timecard_form = TimecardForm(request.POST)
            # print(usermodify_form)
            if timecard_form.is_valid():
                # print(timecard_form.cleaned_data)
                # att_date = timecard_form.cleaned_data['att_date']
                att = Attendance.objects.filter(user=usr, att_date=timecard_form.cleaned_data['att_date'])
                if len(att)==0:
                    att=Attendance()
                    att.att_date=timecard_form.cleaned_data['att_date']
                    att.user=usr
                elif len(att)==1:
                    att=att[0]
                else:
                    att = att[0]
                    print('WRONG IN view_timecard at att')
                att.work_time = timecard_form.cleaned_data['work_time']
                if timecard_form.cleaned_data['proj_occ']=='不选择项目':
                    att.proj_occ=None
                else:
                    att.proj_occ = Project.objects.filter(proj_name=timecard_form.cleaned_data['proj_occ'])[0]
                print(att.proj_occ)
                # proj=Project.objects.filter(proj_name=att.proj_occ)
                # print(proj[0])
                # add1 = Attendance(user=usr, att_date=att_date, work_time=work_time, proj_occ=proj[0])
                print('111111111111111111111111111111')
                att.save()

                return redirect(reverse('att_list'))
        # usermodify_form = UserAppendForm()
        context = {}
        context['timecard_form'] = timecard_form
        return render(request, 'view_timecard.html', context)
    else:
        return redirect(reverse('login'))

def ajax_on_change_tcf(request):
    print(request.POST['time'])
    str_time=request.POST['time']
    atts=Attendance.objects.filter(user=request.user, att_date=str_time)
    if len(atts) == 0:
        return JsonResponse({'msg': 'no result'})
    elif len(atts) == 1:
        return JsonResponse({'msg': '1 result', 'work_time':atts[0].work_time, 'proj_occ':atts[0].get_proj_name()})
    else:
        return JsonResponse({'msg':'wrong'})

attendance/templates/att_list.html
{% extends 'base.html' %}

{% block title %}考勤记录{% endblock %}
{% if user.is_authenticated %}
                        {% block nav_attendance_active %}active{% endblock %}
{% endif %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                <table class="table table-bordered table-hover">
{#                    <span style="margin-right: 1em"><a href="{% url 'order_append' %}">新增订单</a></span>#}
{#                    <span><a href="{% url 'att_list' %}">查找</a></span>#}
                  <thead>
                    <tr>
                      <th scope="col">员工姓名</th>
                        <th scope="col">日期</th>
                      <th scope="col">工作时长</th>
                      <th scope="col">参与项目</th>
{#                         <th scope="col">修改</th>#}
{#                      <th scope="col">删除</th>#}
                    </tr>
                  </thead>
                  <tbody>
                  {%for att in att_list%}
                    <tr>
                      <td>{{att.get_user_name}}</td>
                      <td>{{att.att_date}}</td>
                      <td>{{att.work_time}}</td>
                      <td>{{att.get_proj_name}}</td>
{#                           <td><a href="{% url 'att_modify' order.pk%}">修改</a></td>#}
{#                      <td><a href="{% url 'att_delete' order.pk%}">删除</a></td>#}
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

attendance/templates/view_timecard.html
{% extends 'base.html' %}

{% block title %}timecard{% endblock %}

{% load static %}

{% block content %}
    <body onload="on_load_vtc()"></body>
    <script>
        function on_load_vtc(){
            var date = new Date();
            var date_min = new Date();
            var date_max = new Date();
            date_min.setDate(date_min.getDate() - 3)
            date_max.setDate(date_max.getDate() + 3)
            document.getElementById("id_att_date").setAttribute("min", get_format_date(date_min))
            document.getElementById("id_att_date").setAttribute("max", get_format_date(date_max))
            //alert(get_format_date(date_min))
            //alert(get_format_date(date_max))
        }
        function get_format_date(date){
            var seperator1 = "-";
            var year = date.getFullYear();
            var month = date.getMonth() + 1;
            var strDate = date.getDate();

            if (month >= 1 && month <= 9) {
                month = "0" + month;
            }
            if (strDate >= 0 && strDate <= 9) {
                strDate = "0" + strDate;
            }
            var currentdate = year + seperator1 + month + seperator1 + strDate;
            return currentdate
        }
    </script>
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if user.is_authenticated %}
                    <div class="panel panel-default" style="margin-top: 2em">
                        <div class="panel-heading">
                            <h3 class="panel-title">考勤卡</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in timecard_form %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger">{{ login_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <input type="button" value="取消" class="btn btn-primary pull-left">
                                <input type="submit" value="提交" class="btn btn-primary pull-right">
                            </form>
                        <script>
                            function on_change_tcf(){
                                //alert(typeof event.srcElement.value)
                                var time_cg=event.srcElement.value
                                $.ajax({
                                    url: "{% url 'ajax_on_change_tcf' %}",
                                    type: "POST",
                                    data: {time: time_cg},
                                    success:function (data){
                                        //alert(data['test'])
                                        if(data['msg']==='no result'){
                                            //alert(event.srcElement.value)
                                            alert(time_cg+'未考勤')
                                            $("#id_work_time").val("")
                                            $("#id_proj_occ").val("")
                                        }
                                        else if(data['msg']==='1 result'){
                                            $("#id_work_time").val(data['work_time'])
                                            $("#id_proj_occ").val(data['proj_occ'])
                                        }
                                        else{
                                            alert('WRONG!')
                                        }
                                    }
                                })
                            }
                        </script>
                        </div>
                    </div>
                {% else %}
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}