factory/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('orders/', include('orders.urls')),
    path('notice/', include('notice.urls')),
    path('attendance/', include('attendance.urls')),
    path('report/', include('report.urls')),
    path('projectmanagement/', include('projectmanagement.urls')),
    path('payroll/', include('payroll.urls')),
    path('trashcan/', include('trashcan.urls'))
]

report/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('admin_report/', views.admin_report, name='admin_report'),
    path('employee_report/', views.employee_report, name='employee_report'),
]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #path('login_for_medal/', views.login_for_medal, name='login_for_medal'),
    path('login/', views.login, name='login'),
    path('userappend/', views.userappend, name='userappend'),
    path('user_normal_select/', views.user_normal_select, name='user_normal_select'),
    path('logout/', views.logout, name='logout'),
    path('user_info/', views.user_info, name='user_info'),
    path('user_list/', views.user_list, name='user_list'),
    path('user_select/', views.user_select, name='user_select'),
    # path('attendence_list/<int:user_pk>', views.attendence_list, name='attendence_list'),
    # path('attendence_lists/', views.attendence_lists, name='attendence_lists'),
    path('position_lists/', views.position_lists, name='position_lists'),
    path('staff_type_modify/<int:position_pk>', views.staff_type_modify, name='staff_type_modify'),
    path('staff_type_add/', views.staff_type_add, name='staff_type_add'),
    path('staff_type_delete/<int:position_pk>', views.staff_type_delete, name='staff_type_delete'),
    path('salary_list/<int:user_pk>', views.salary_list, name='salary_list'),
    path('salary_lists/', views.salary_lists, name='salary_lists'),
    path('caculate_salary/', views.caculate_salary, name='caculate_salary'),
    path('salary_normal_select/', views.salary_normal_select, name='salary_normal_select'),
    path('salary_select/', views.salary_select, name='salary_select'),
    #path('change_nickname/', views.change_nickname, name='change_nickname'),
    #path('bind_email/', views.bind_email, name='bind_email'),
    #path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('change_password/', views.change_password, name='change_password'),
    #path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('user_delete/<int:user_pk>', views.user_delete, name='user_delete'),
    path('user_modify/<int:user_pk>', views.usermodify, name='user_modify'),
    # path('attendence_append/', views.attendence_append, name='attendence_append'),
    # path('attendence_select/', views.attendence_select, name='attendence_select'),
    # path('attendence_delete/<int:attendence_pk>', views.attendence_delete, name='attendence_delete'),
    # path('attendence_modify/<int:attendence_pk>', views.attendence_modify, name='attendence_modify'),
    path('sel_pay_m', views.sel_pay_m, name='sel_pay_m'),
]

report/models.py
from django.db import models

# Create your models here.

report/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.forms import widgets
from projectmanagement.models import Project


class SelForm(forms.Form):

    report_type = forms.CharField(
        label='选择日期',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.Select(choices=[('工作总时长', '工作总时长'), ('工资支付情况', '工资支付情况')])
    )

    start_date = forms.DateField(
        label='选择开始日期',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    end_date = forms.DateField(
        label='选择截止日期',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    emp_names = forms.CharField(
        label='员工姓名',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入员工姓名，多个员工用/分开'})
    )

class EmpForm(forms.Form):
    ps = Project.objects.all()
    proj = [('不选择项目', '不选择项目')]
    for p in ps:
        proj.append((p.proj_name, p.proj_name))
    report_type = forms.CharField(
        label='选择查询',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.Select(choices=[('工作总时长', '工作总时长'), ('工资支付情况', '工资支付情况')])
    )

    start_date = forms.DateField(
        label='选择开始日期',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    end_date = forms.DateField(
        label='选择截止日期',
        # widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入交货时间'})
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    proj_occ = forms.CharField(
        label='项目名称',
        widget=forms.Select(choices=proj),
    )

class EmpResForm(forms.Form):
    toth = forms.FloatField(
        label='工作总时长',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''})
    )
    tosal = forms.FloatField(
        label='工资支付金额',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''})
    )

report/views.py
from django.shortcuts import render
from django.shortcuts import render,get_object_or_404, redirect
from django.urls import reverse
from .forms import SelForm
from attendance.models import Attendance
from django.contrib.auth.models import User
import datetime
from orders.models import Orders
from .forms import EmpForm, EmpResForm
from django.http.response import JsonResponse

# Create your views here.

def admin_report(request):
    user = request.user
    if user.is_authenticated:
        if request.method == 'POST':
            selform = SelForm(request.POST)
            if selform.is_valid():
                start_date=selform.cleaned_data['start_date']
                end_date = selform.cleaned_data['end_date']
                emp_names = selform.cleaned_data['emp_names']
                emp_names = emp_names.split('/')
                res=[]
                for e in emp_names:
                    if len(User.objects.filter(username=e)) == 0:
                        continue
                    e_usr=User.objects.filter(username=e)[0]
                    toth=sum([att.work_time for att in Attendance.objects.filter(user=e_usr, att_date__range=(start_date, end_date))])
                    tot_sal=0.0
                    if e_usr.get_staff_type() == '小时工':
                        # print(last_date.last_run_date)
                        # print(type(last_date.last_run_date))
                        sph = e_usr.get_salary_pre_hour()
                        atts = Attendance.objects.filter(user=e_usr, att_date__range=(
                        start_date, end_date))
                        toth = 0.0
                        for att in atts:
                            toth += att.work_time
                        tot_sal = toth * sph
                        # print(r['salary'])
                    elif e_usr.get_staff_type() == '受薪雇员':
                        sal = e_usr.get_user_profile().salary
                        atts = Attendance.objects.filter(user=e_usr,
                                                         att_date__range=(
                                                         start_date, end_date))
                        tot_sal = len(atts) / 30 * sal
                    elif e_usr.get_staff_type() == '委托员工':
                        sal = e_usr.get_user_profile().salary
                        atts = Attendance.objects.filter(user=e_usr,
                                                         att_date__range=(
                                                         start_date, end_date))
                        ords = Orders.objects.filter(creator=e_usr)
                        tot_o_val = sum([o.order_total_price for o in ords])
                        tot_sal = len(atts) / 30 * sal + tot_o_val * e_usr.get_user_profile().com_rate
                    else:
                        print(e_usr.get_staff_type())
                    res.append({'name':e, 'tot_time':toth, 'tot_sal':tot_sal})
                return render(request, 'admin_report.html', {'res': res})
            else:
                return render(request, 'sel_rep_meth.html', {'selform': selform})
        else:
            selform=SelForm()

            return render(request, 'sel_rep_meth.html', {'selform':selform})
    else:
        return redirect(reverse('login'))


def employee_report(request):
    user = request.user
    if user.is_authenticated:
        if request.method == 'POST':
            start_date = request.POST['st_date']
            end_date = request.POST['ed_date']
            if request.POST['proj_occ'] == '不选择项目':
                toth=sum([att.work_time for att in Attendance.objects.filter(user=user, att_date__range=(start_date, end_date))])
            else:
                toth=sum([att.work_time for att in Attendance.objects.filter(user=user, att_date__range=(start_date, end_date),
                                                                             proj_occ__proj_name=request.POST['proj_occ'])])
            tot_sal = 0.0
            if user.get_staff_type() == '小时工':
                # print(last_date.last_run_date)
                # print(type(last_date.last_run_date))
                sph = user.get_salary_pre_hour()
                atts = Attendance.objects.filter(user=user, att_date__range=(
                    start_date, end_date))
                toth = 0.0
                for att in atts:
                    toth += att.work_time
                tot_sal = toth * sph
                # print(r['salary'])
            elif user.get_staff_type() == '受薪雇员':
                sal = user.get_user_profile().salary
                atts = Attendance.objects.filter(user=user,
                                                 att_date__range=(
                                                     start_date, end_date))
                tot_sal = len(atts) / 30 * sal
            elif user.get_staff_type() == '委托员工':
                sal = user.get_user_profile().salary
                atts = Attendance.objects.filter(user=user,
                                                 att_date__range=(
                                                     start_date, end_date))
                ords = Orders.objects.filter(creator=user)
                tot_o_val = sum([o.order_total_price for o in ords])
                tot_sal = len(atts) / 30 * sal + tot_o_val * user.get_user_profile().com_rate
            else:
                print(user.get_staff_type())

            return JsonResponse({'toth': toth, 'tot_sal': tot_sal})
        else:
            empresform = EmpResForm()
            return render(request, 'emp_report.html', {'empform':EmpForm(), 'empresform':empresform})
    else:
        return redirect(reverse('login'))

report/templates/admin_report.html
{% extends 'base.html' %}

{% block title %}admin_report{% endblock %}
{% if user.is_authenticated %}
                        {% block nav_report_admin_active %}active{% endblock %}
{% endif %}
{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                <table class="table table-bordered table-hover">
{#                    <span style="margin-right: 1em"><a href="{% url 'order_append' %}">新增订单</a></span>#}
                    <span><a href="{% url 'att_list' %}">查找</a></span>
                  <thead>
                    <tr>
                      <th scope="col">员工姓名</th>
                        <th scope="col">所获工资</th>
                      <th scope="col">工作时长</th>

{#                         <th scope="col">修改</th>#}
{#                      <th scope="col">删除</th>#}
                    </tr>
                  </thead>
                  <tbody>
                  {%for r in res%}
                    <tr>
                      <td>{{ r.name }}</td>
                      <td>{{ r.tot_sal}}</td>
                      <td>{{ r.tot_time }}</td>

{#                           <td><a href="{% url 'att_modify' order.pk%}">修改</a></td>#}
{#                      <td><a href="{% url 'att_delete' order.pk%}">删除</a></td>#}
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
                    <form action="{% url 'run_payroll' %}" method="get">
                    <input type="submit" value="确认支付" class="btn btn-primary pull-right">
                    </form>

                {% else %}
                    <span>未登录，跳转到首页...</span>
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

report/templates/emp_report.html
{% extends 'base.html' %}

{% block title %}timecard{% endblock %}

{% load static %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if user.is_authenticated %}
                    <div class="panel panel-default" style="margin-top: 2em">
                        <div class="panel-heading">
                            <h3 class="panel-title">查询记录</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in empform %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger">{{ login_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
{#                                <input type="button" value="取消" class="btn btn-primary pull-left">#}
                                <input type="button" value="查询" class="btn btn-primary pull-right" onclick="on_submit_empq()">
                            </form>
                        <script>
                            function on_submit_empq(){
                                //alert(typeof event.srcElement.value)
                                $.ajax({
                                    url: "{% url 'employee_report' %}",
                                    type: "POST",
                                    data: {
                                        report_type: $("#id_report_type").val(),
                                        st_date: $("#id_start_date").val(),
                                        ed_date: $("#id_end_date").val(),
                                        proj_occ: $("#id_proj_occ").val()
                                    },
                                    success:function (data){
                                        //alert(data['test'])
                                        $("#id_toth").val(data['toth'])
                                        $("#id_tosal").val(data['tot_sal'])
                                    }
                                })
                            }
                        </script>
                        </div>
                    </div>

                    <div class="panel panel-default" style="margin-top: 2em">
                        <div class="panel-heading">
                            <h3 class="panel-title">考勤卡</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in empresform %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger">{{ login_form.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <input type="button" value="取消" class="btn btn-primary pull-left">
                                <input type="submit" value="提交" class="btn btn-primary pull-right">
                            </form>
                        </div>
                    </div>
                {% else %}
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

report/templates/sel_rep_meth.html
{% extends 'base.html' %}

{% load static %}

{% block title %}选择报告方式{% endblock %}

{% if user.is_authenticated %}
                        {% block nav_report_admin_active %}active{% endblock %}
{% endif %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                {% if user.is_authenticated %}
                    <div class="panel panel-default" style="margin-top: 2em">
                        <div class="panel-heading">
                            <h3 class="panel-title">修改</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="POST">
                                {% csrf_token %}
                                {% for field in selform %}
                                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger">{{ selform.non_field_errors }}</span>
                                <div class="clearfix"></div>
                                <input type="button" value="取消" class="btn btn-primary pull-left">
                                <input type="submit" value="提交" class="btn btn-primary pull-right">
                            </form>
                        <script src="{% static 'js/func_change.js' %}"></script>
                        </div>
                    </div>
                {% else %}
                    <script type="text/javascript">
                        window.location.href = '/';
                    </script>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}